title: "Derek Olmstead"
description: "Employment, research, publications, and education"
remote_theme: "mmistakes/minimal-mistakes"

# recommended settings
plugins:
  - jekyll-include-cache

# optional: add social links
author:
  name: "Derek Olmstead"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:derek.olmstead@ucalgary.ca"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/derekolmstead"
